name: Pool Order

on:
  pull_request:
    branches:
      - master

jobs:
  pool_order_changed_files:
    runs-on: ubuntu-latest
    outputs:
      json: ${{steps.changed-files-specific.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.6
        with:
          files: |
            pool-order.json

  format_check:
    runs-on: ubuntu-latest
    needs: pool_order_changed_files
    if: needs.pool_order_changed_files.outputs.json == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
      - run: npm install
        shell: bash
      - run: npm run test
        shell: bash
